
export const SKIP_QUESTION = 'SKIP_QUESTION';
export const MARK_ANSWER = 'MARK_ANSWER';
export const MARK_ANSWER_CORRECT = 'MARK_ANSWER_CORRECT';


export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';
