
//Questions
export const SKIP_QUESTION = 'SKIP_QUESTION';
export const MARK_ANSWER = 'MARK_ANSWER';
export const MARK_ANSWER_CORRECT = 'MARK_ANSWER_CORRECT';
export const MARK_ANSWER_WRONG = 'MARK_ANSWER_WRONG';
export const POPULATE_ANSWER_STATS = 'POPULATE_ANSWER_STATS';

//AUth
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

//Timer
export const RESET_PER_QUESTION_TIMER = 'RESET_PER_QUESTION_TIMER';
export const INCREMENT_PER_QUESTION_TIMER = 'INCREMENT_PER_QUESTION_TIMER';
export const SET_START_TO_FALSE = 'SET_START_TO_FALSE';
